name = "pb"
compatibility_date = "2023-01-28"

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*.html", "*.client.js", "*.md", "*.css" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "shz.al"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "cc398e983a234aa19de5ea6af571a483"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://shz.al"

# url to repo, displayed in index page
REPO = "https://github.com/SharzyL/pastebin-worker"

# url to favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "Sharzy"

# the email displayed in TOS
TOS_MAIL = "pb@shz.al"

