name = "pb"
compatibility_date = "2023-01-28"

workers_dev = false
main = "src/index.js"
vars = { ENVIRONMENT = "production" }

# change the pattern to your domain name
route = { pattern = "shz.al", custom_domain = true }

# change the id to your KV id
kv_namespaces = [
  { binding = "PB", id = "cc398e983a234aa19de5ea6af571a483" },
]

# the following content is used for testing, may be removed if you do not need
[env.preview]
vars = { ENVIRONMENT = "preview" }
route = { pattern = "pb-preview.shz.al", custom_domain = true }
minify = false

kv_namespaces = [
  { binding = "PB", id = "f56ae0043abd4bb4ab61c52071bd9c7f" }
]

