name: docker

on:
  workflow_dispatch:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

permissions:
  packages: write

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # https://github.com/docker/login-action
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # https://github.com/docker/metadata-action
    - name: Generate Docker tags
      uses: docker/metadata-action@v5
      id: metadata
      with:
        images: |
          mikf123/gallery-dl
          ghcr.io/mikf/gallery-dl
        tags: |
          type=sha,format=long,prefix=
          type=ref,event=tag

    # https://github.com/docker/build-push-action
    - name: Build image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        platforms: linux/amd64
