name: executables

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macOS-latest"]
        architecture: ["x64"]
        python-version: ["3.12"]
        python-packages: [""]
        include:
        - os: "ubuntu-latest"
          architecture: "x64"
          python-version: "3.12"
          python-packages: "secretstorage"
        - os: "windows-2019"
          architecture: "x86"
          python-version: "3.8"
          python-packages: "toml"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Build executable
      run: |
        pip install requests requests[socks] yt-dlp pyyaml ${{ matrix.python-packages }} pyinstaller
        python scripts/pyinstaller.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: gallery-dl-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
        path: |
          dist
