name: Dispatch GitHub Pages Build

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch
      run: >
        curl -L
        -X POST
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/gdl-org/docs/actions/workflows/pages.yml/dispatches
        -d '{"ref":"master"}'
